### ISSUE TITLE
Add support for JDBC connection to be able connect to any RDBMS

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#430]
1. add configuration:
```
storage: jdbc
storage_configuration:
    driver: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://hostname:port/database
    username: user
    password: secret
```
2. add dynamic loading for driver `Class.forName("com.mysql.jdbc.Driver")`
3. add detailed instructions to docs 
4. test it with at least Postgres, MySql.
