### ISSUE TITLE
Add persistence manager support from oxcore

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#477]
We should add persistence manager support from oxcore.

It means 2 possible values for `storage`:

- `ldap` -> creates `org.gluu.persist.ldap.impl.LdapEntryManager`
- `couchbase` -> creates `org.gluu.persist.couchbase.impl.CouchbaseEntryManager`

Entry managers should be created via factories:
- org.gluu.persist.couchbase.impl.CouchbaseEntryManagerFactory#createEntryManager
- org.gluu.persist.ldap.impl.LdapEntryManagerFactory#createEntryManager

Docs should be updated accordingly with ldap and couchbase configuration properties.

**Comment by yuriyz** [comment]
For convenient it would be nice to support one more option to point to Gluu Server configuration files to pick up connection (for `ldap` and `couchbase` we should mirror it in `oxd-server.yml`).
```
storage: gluu_server_configuration
storage_configuration:
    type: /gluu-server/etc/gluu/conf/gluu.properties
    connection: /gluu-server/etc/gluu/conf/gluu-ldap.properties
```
